USE schedule;

CREATE TABLE MEMBER
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE schedule
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(40) NOT NULL,
    contents VARCHAR(255) NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SCHEDULE_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBER (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE comment
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    comment VARCHAR(255) NOT NULL,
    member_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBER (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_COMMENT_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedule (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)
